### ISSUE TITLE
Epic: File IO in application level

### ISSUE THREAD

**Issue by dmpetrov** [iterative/datachain#33]
```[tasklist]
### Must have for the release
- [ ] iterative/dvcx#1635
- [ ] iterative/datachain#32
- [ ] iterative/datachain#34
- [ ] iterative/datachain#35
- [ ] iterative/datachain#36
- [ ] iterative/datachain#37
- [ ] https://github.com/iterative/datachain/issues/212
```

```[tasklist]
### Nice-to-have for the release
- [ ] iterative/datachain#38
- [ ] iterative/datachain#39
- [ ] iterative/datachain#40
- [ ] File diff
```

```[tasklist]
### Next steps
- [ ] https://github.com/iterative/datachain/issues/743
- [ ] iterative/dvcx#1358 (re-implemented async)
```

**Comment by shcheklein** [comment]
@dreadatour @dmpetrov can you please add a bit more details on diff and on recent examples from customers. It is the last item that is left here.

**Comment by ilongin** [comment]
@shcheklein I spoke with Dmitry and we decided that `diff` should be like this: https://github.com/iterative/datachain/issues/636 ... I will start working on it soon.

**Comment by dmpetrov** [comment]
This epic seems done 🎉 
Closing

**Comment by dmpetrov** [comment]
Let's work on diff() and data upload separately
