### ISSUE TITLE
Epic: move indexing to an application layer

### ISSUE THREAD

**Issue by skshetry** [iterative/datachain#39]
### Description

i.e make it based on a feature schema and if possible, with udfs.

```[tasklist]
### Subtasks
- [ ] https://github.com/iterative/datachain/issues/246
- [ ] https://github.com/iterative/datachain/issues/244
- [ ] https://github.com/iterative/datachain/issues/266
- [ ] https://github.com/iterative/datachain/issues/317
- [ ] https://github.com/iterative/datachain/issues/318
- [ ] https://github.com/iterative/datachain/issues/329
- [ ] https://github.com/iterative/datachain/issues/340
- [ ] https://github.com/iterative/datachain/issues/447
```

**Comment by dmpetrov** [comment]
> I think we should start getting rid of partials. T

and

> that this can all be done even without that partials table, just on the fly but this needs to be investigated.

Both are good ideas! Let's try to simplify this as much as we can.


> We need to think how to deal with additional tables that are created during indexing, like buckets or partials. So this is not just normal UDF that has an output of some rows in a dataset table

Right. We need to find a way to fit the buckets (as well as partials i if needed) into "just normal UDF" and normal datasets. I hope these datasets won't be visible to users (by default).

**Comment by ilongin** [comment]
I can take over this one and make a plan / subtasks
